development:
  adapter: postgresql
  encoding: utf8
  database: Project-2-enhanced_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: Project-2-enhanced_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: Project-2-enhanced_production
  pool: 5
